import { ref } from 'vue';

export type Locale = 'es' | 'en';
export type Theme = 'light' | 'dark';

const locale = ref<Locale>((localStorage.getItem('mangago-locale') as Locale) || 'es');
const theme = ref<Theme>((localStorage.getItem('mangago-theme') as Theme) || 'light');

const messages: Record<Locale, Record<string, string>> = {
  es: {
    'alerts.title': 'Avísame cuando haya stock',
    'alerts.description': 'Déjanos tu correo y te avisaremos cuando este volumen vuelva a estar disponible.',
    'alerts.email': 'Tu correo electrónico', 'alerts.submit': 'Quiero recibir el aviso', 'alerts.sending': 'Procesando…',
    'alerts.consent': 'Quiero recibir el correo de confirmación y un aviso de disponibilidad de este volumen. Puedo cancelar desde el correo. El aviso vence a los 90 días.',
    'alerts.registered': 'Solicitud recibida. Revisa tu correo, incluida la carpeta de spam, y activa el aviso desde el enlace. Si ya lo activaste, no necesitas registrarte otra vez.',
    'alerts.failed': 'No pudimos procesar la solicitud. Intenta de nuevo en unos minutos.',
    'alerts.rateLimit': 'Has enviado varias solicitudes. Espera unos minutos antes de intentar otra vez.',
    'alerts.inStock': 'Este volumen ya tiene stock. Cierra la ficha y actualiza el catálogo para verlo.',
    'alerts.unavailable': 'Los avisos por correo no están disponibles por el momento. Intenta más tarde.',
    'alerts.activateTitle': 'Activar aviso', 'alerts.cancelTitle': 'Cancelar aviso',
    'alerts.manageDescription': 'Confirma tu elección para gestionar el aviso de este volumen.',
    'alerts.invalidLink': 'El enlace no es válido o ha vencido. Puedes solicitar un nuevo aviso desde el catálogo.',
    'alerts.activated': 'Aviso activado. Te enviaremos un correo cuando haya stock. No reserva un ejemplar y vence a los 90 días.',
    'alerts.cancelled': 'Aviso cancelado. Ya no recibirás notificaciones de esta suscripción.',
    'nav.catalog': 'Catálogo', 'nav.new': 'Novedades', 'nav.collections': 'Colecciones', 'nav.rentals': 'Alquileres', 'nav.help': 'Ayuda', 'nav.cart': 'Carrito',
    'nav.main': 'Navegación principal', 'nav.open': 'Abrir menú', 'nav.close': 'Cerrar menú', 'nav.theme': 'Cambiar tema', 'nav.language': 'Cambiar idioma',
    'home.eyebrow': 'Tu próxima lectura empieza aquí', 'home.title': 'Historias que te llevan', 'home.titleAccent': 'a otros mundos.',
    'home.description': 'Descubre tu próxima serie favorita. Explora títulos y consulta los precios y la disponibilidad de cada volumen.',
    'home.explore': 'Explorar mangas', 'home.how': '¿Cómo funciona?', 'home.volume': 'Información por volumen', 'home.stock': 'Disponibilidad visible',
    'home.readers': 'Favoritos de la comunidad', 'home.popular': 'En boca de todos', 'home.popularDescription': 'Las historias que están conquistando a quienes leen con nosotros.',
    'home.recent': 'Nuevas historias', 'home.recentDescription': 'Descubre los últimos títulos que sumamos al catálogo.', 'home.loading': 'Cargando…',
    'home.trendLoading': 'Buscando las historias favoritas…', 'home.trendEmpty': 'Pronto encontrarás recomendaciones aquí.', 'home.arrivalsLoading': 'Cargando novedades…', 'home.arrivalsEmpty': 'Estamos preparando más novedades para ti.', 'home.arrivalsEyebrow': 'Acaban de llegar', 'home.latestDescription': 'Descubre los últimos títulos que sumamos al catálogo.', 'home.available': 'Disponible', 'home.none': 'Sin stock', 'home.rentalDay': 'Alquiler', 'home.purchasePrice': 'Compra', 'home.authorEyebrow': 'Quienes dan vida a cada página', 'home.authorsTitle': 'Autores que dejan huella', 'home.authorsDescription': 'Conoce a los creadores que más está leyendo la comunidad.', 'home.authorsLoading': 'Cargando autores…', 'home.authorsEmpty': 'Los autores más leídos aparecerán aquí.', 'home.reading': 'Lecturas que nos unen', 'home.community': 'Lo que la comunidad está leyendo', 'home.week': '📖 Más leídos esta semana', 'home.weekEmpty': 'Aún no hay lecturas para mostrar.', 'home.today': '🔥 Más alquilados hoy', 'home.todayEmpty': 'Los alquileres de hoy aparecerán aquí.', 'home.volumes': 'títulos', 'home.titleSingular': 'título', 'home.featured': 'Selección de lectores', 'home.recommendation': 'Una recomendación para ti', 'home.featuredDetails': 'Ver detalles', 'home.awaiting': 'Una nueva historia te está esperando', 'home.sticker': 'Lee a tu ritmo', 'home.collectionsEyebrow': 'Encuentra tu próximo mundo', 'home.collectionsTitle': 'Lee según tu estado de ánimo', 'home.collectionsDescription': 'Una puerta de entrada para cada tipo de lector.', 'home.collectionBeginner': 'Empieza por aquí', 'home.collectionAnime': 'Del anime a las páginas', 'home.collectionHorror': 'Misterio para leer de noche',
    'home.collectionLoading': 'Buscando títulos…', 'home.collectionEmpty': 'No hay mangas disponibles en esta colección.', 'home.scrollCollection': 'Desplazarse por la colección', 'home.infoEyebrow': 'Un catálogo para explorar', 'home.infoTitle': 'Descubre títulos y consulta sus datos.', 'home.exploreStories': 'Explora historias', 'home.browseCollections': 'Recorre novedades y colecciones', 'home.findGenres': 'Encuentra títulos por género', 'home.ratings': 'Mira las valoraciones disponibles', 'home.openDetails': 'Abre la ficha', 'home.synopsis': 'Revisa autor y sinopsis', 'home.buyPrice': 'Consulta precio de compra', 'home.rentalRate': 'Mira tarifa de alquiler diaria', 'home.recordedStock': 'Comprueba el stock registrado', 'home.internalRentals': 'Alquileres internos', 'home.staffRental': 'El equipo registra el alquiler', 'home.returnDate': 'Se fija una fecha de devolución', 'home.inventoryUpdate': 'El panel actualiza el inventario', 'home.testCheckout': 'Compra en modo de prueba', 'home.checkoutReserve': 'La reserva se inicia al comenzar el pago', 'home.mixedCart': 'Las compras y alquileres comparten carrito', 'home.testCards': 'Stripe Checkout usa tarjetas de prueba', 'home.serviceStatus': 'Ver estado del servicio',
    'footer.tagline': 'Un lugar para descubrir historias, probar nuevas series y encontrar tu próxima favorita.', 'footer.help': '¿Necesitas ayuda?', 'footer.explore': 'Explora',
    'footer.info': 'Información', 'footer.faq': 'Preguntas frecuentes', 'footer.return': 'Política de devolución', 'footer.terms': 'Términos y condiciones', 'footer.top': 'Volver arriba ↑', 'footer.popular': 'Favoritos de lectores', 'footer.rentals': 'Políticas de alquiler', 'footer.exploreLabel': 'Explorar tienda', 'footer.infoLabel': 'Información', 'footer.backTop': 'Volver al inicio', 'footer.note': 'Una página a la vez. Un mundo nuevo en cada historia.',
    'catalog.eyebrow': 'Tu próxima lectura', 'catalog.title': 'Explora el catálogo', 'catalog.description': 'Encuentra el manga y volumen que buscas. Filtra por disponibilidad, compra o alquiler.', 'catalog.search': 'Buscar', 'catalog.manga': 'Manga', 'catalog.allManga': 'Todos los mangas', 'catalog.volume': 'Volumen', 'catalog.allVolumes': 'Todos los volúmenes', 'catalog.author': 'Autor', 'catalog.allAuthors': 'Todos los autores', 'catalog.availability': 'Disponibilidad', 'catalog.allStock': 'Con o sin stock', 'catalog.available': 'Con stock', 'catalog.unavailable': 'Sin stock', 'catalog.mode': 'Modalidad', 'catalog.buyRent': 'Compra y alquiler', 'catalog.purchase': 'Para compra', 'catalog.rental': 'Para alquiler', 'catalog.clear': 'Limpiar filtros', 'catalog.loading': 'Cargando catálogo…', 'catalog.notFound': 'No hay mangas para esta combinación de filtros. Prueba a cambiar alguno.', 'catalog.previous': 'Anterior', 'catalog.next': 'Siguiente', 'catalog.retry': 'Reintentar', 'catalog.foundOne': 'volumen encontrado', 'catalog.foundMany': 'volúmenes encontrados',
    'cart.selection': 'Tu selección', 'cart.title': 'Tu carrito', 'cart.description': 'Combina volúmenes para comprar y alquilar en una sola revisión.', 'cart.continue': '← Seguir explorando', 'cart.summary': 'Resumen', 'cart.order': 'Tu pedido', 'cart.items': 'Artículos', 'cart.total': 'Total estimado', 'cart.checkout': 'Continuar al pago', 'cart.empty': 'Tu carrito está vacío', 'cart.emptyText': 'Agrega un volumen para comprarlo o alquilarlo y aparecerá aquí.', 'cart.explore': 'Explorar catálogo', 'cart.remove': 'Quitar', 'cart.quantity': 'Cantidad', 'cart.days': 'Días de alquiler', 'cart.buy': 'Compra', 'cart.rent': 'Alquiler', 'cart.outOfStock': 'Sin stock disponible', 'cart.available': 'en stock', 'cart.insufficient': 'Stock insuficiente para el carrito', 'cart.noReservation': 'El carrito no reserva unidades', 'cart.stockChanged': 'Revisa las cantidades: algún volumen ya no tiene stock suficiente.', 'cart.testPayment': 'Stripe Checkout en modo de prueba · no se aceptan pagos reales', 'cart.cancelled': 'Pago cancelado. Liberamos las unidades reservadas; puedes volver a intentarlo.', 'cart.cancelling': 'El pago se canceló. La reserva se está liberando; recarga la tienda en unos minutos.',
    'faq.center': 'Centro de ayuda', 'faq.title': 'Respuestas para seguir leyendo.', 'faq.intro': 'Entiende qué ofrece el catálogo y cómo funcionan las compras y alquileres en modo de prueba.', 'faq.view': 'Ver preguntas frecuentes', 'faq.useful': 'Información útil', 'faq.details': '¿Buscas todos los detalles?', 'faq.version': 'Revisa lo que puede hacer el sistema en esta versión.', 'faq.rentalPolicies': 'Políticas de alquiler', 'faq.returns': 'Devoluciones y reembolsos', 'faq.terms': 'Términos y condiciones', 'faq.next': 'A un paso de tu próxima historia', 'faq.faqs': 'Preguntas frecuentes', 'faq.searchHint': 'Busca un tema o abre una pregunta para ver su respuesta.', 'faq.search': 'Buscar en preguntas frecuentes', 'faq.placeholder': 'Prueba: alquiler, pago o devolución', 'faq.one': 'resultado', 'faq.many': 'resultados', 'faq.notFound': 'No encontramos esa pregunta', 'faq.tryAgain': 'Prueba con otra palabra, como alquiler, entrega o pago.', 'faq.clear': 'Borrar búsqueda',
    'faq.q1': '¿Puedo comprar o alquilar desde la tienda?', 'faq.a1': 'Puedes combinar compras y alquileres en un mismo carrito y continuar a Stripe Checkout en modo de prueba. Al iniciar el pago, el sistema reserva stock temporalmente; una operación aprobada queda en Pedidos y los alquileres aparecen en el panel.', 'faq.q2': '¿Qué significa el precio de alquiler?', 'faq.a2': 'El catálogo muestra la tarifa diaria configurada para cada volumen. El panel interno calcula el costo de un alquiler según los días registrados; desde esta tienda todavía no se puede iniciar ese proceso.', 'faq.q3': '¿Cómo consulto si hay ejemplares disponibles?', 'faq.a3': 'Abre la ficha de un manga desde una tarjeta del catálogo para ver el stock que figura actualmente en el sistema. Esa cantidad es informativa y no reserva un ejemplar.', 'faq.q4': '¿Cómo se registra una devolución?', 'faq.a4': 'Actualmente el equipo marca la devolución desde el panel administrativo. El sitio público no programa recogidas ni ofrece un historial personal de alquileres.', 'faq.q5': '¿Cuáles son los plazos y cargos de alquiler?', 'faq.a5': 'Los períodos fijos, depósitos, recargos por retraso, descuentos y condiciones de entrega todavía no están confirmados en esta versión. No se anuncian como condiciones del servicio hasta que el negocio los defina.', 'faq.q6': '¿Qué medios de pago puedo usar?', 'faq.a6': 'La tienda usa Stripe Checkout en modo de prueba. Se necesita configurar las claves de prueba en el servidor y no se procesan cobros reales.', 'faq.q7': '¿Dónde encuentro todas las condiciones?', 'faq.a7': 'Aquí tienes las páginas con el detalle de cada servicio. Si una condición no está clara, revisa la información correspondiente al producto antes de continuar.', 'faq.linkRental': 'Estado de los alquileres', 'faq.linkHowRental': 'Cómo funciona el alquiler', 'faq.linkReturns': 'Estado de las devoluciones', 'faq.linkTerms': 'Leer términos del proyecto', 'faq.linkSystem': 'Ver información del sistema', 'faq.linkRentals': 'Alquileres', 'faq.linkReturn': 'Devoluciones', 'faq.linkTermsShort': 'Términos',
    'policy.rentalEyebrow': 'Alquileres', 'policy.rentalTitle': 'Cómo funciona hoy', 'policy.rentalDescription': 'Una guía clara sobre la información que ofrece el catálogo y lo que el sistema puede gestionar en esta versión.', 'policy.rentalNotice': 'Las condiciones comerciales finales —duración, depósito, cargos por retraso, entregas y pagos— todavía deben ser confirmadas por el negocio. Esta página describe solo el comportamiento que existe en la aplicación.', 'policy.catalog': 'LO QUE PUEDES CONSULTAR', 'policy.volumePrice': 'Precios y disponibilidad por volumen', 'policy.volumeDescription': 'La tienda muestra los títulos del catálogo, el volumen, el precio de compra, la tarifa de alquiler por día y las unidades registradas en inventario.', 'policy.internal': 'GESTIÓN INTERNA', 'policy.rentalRecords': 'Registro de alquileres', 'policy.rentalManagement': 'El panel permite al equipo crear un alquiler para un cliente y un manga con stock disponible, fijar una fecha de devolución y consultar el estado del alquiler.', 'policy.stock': 'Stock', 'policy.stockDescription': 'Al registrar un alquiler, se reserva una unidad. Al marcar la devolución, esa unidad vuelve al inventario.', 'policy.calculation': 'Cálculo', 'policy.calculationDescription': 'El sistema calcula el costo usando la tarifa diaria configurada para el manga y los días hasta la fecha de devolución.', 'policy.payment': 'Pago', 'policy.paymentDescription': 'El checkout de la tienda procesa pagos de prueba mediante Stripe. Los alquileres aprobados se registran como pagados en el panel administrativo.', 'policy.pending': 'PENDIENTE DE DEFINIR', 'policy.conditions': 'Condiciones comerciales', 'policy.conditionsDescription': 'La versión actual no configura periodos fijos, extensiones, depósitos, descuentos, multas, cobertura de entrega ni medios de pago. Esos valores deben definirse antes de anunciarlos como condiciones del servicio.',
    'checkout.order': 'Pedido de tienda', 'checkout.receipt': 'Comprobante interno', 'checkout.customer': 'Cliente', 'checkout.rental': 'alquiler', 'checkout.purchase': 'compra', 'checkout.days': 'días', 'checkout.total': 'Total pagado', 'checkout.nonFiscal': 'Comprobante interno sin validez fiscal · Pago de prueba', 'checkout.backCatalog': 'Volver al catálogo', 'checkout.print': 'Imprimir comprobante', 'checkout.backCart': 'Volver al carrito', 'checkout.explore': 'Explorar catálogo', 'checkout.confirming': 'Confirmando tu pago', 'checkout.waiting': 'Stripe recibió el regreso. Esperamos la confirmación segura del pago; puedes dejar esta página abierta.', 'checkout.notFound': 'No encontramos la sesión', 'checkout.returnCart': 'Regresa al carrito para iniciar el checkout de nuevo.', 'checkout.confirmed': '¡Pedido confirmado!', 'checkout.approved': 'El pago de prueba fue aprobado, las unidades quedaron asignadas y guardamos tu comprobante.', 'checkout.incomplete': 'El pago no se completó', 'checkout.released': 'No se cobró el pedido y la reserva de inventario se liberó. Puedes volver a intentarlo.', 'checkout.verifyFailed': 'No pudimos verificar el pago', 'checkout.checkLater': 'Revisa el estado del pedido en unos momentos desde el soporte de la tienda.', 'checkout.pending': 'La confirmación aún está en proceso. Actualiza esta página en unos segundos; no vuelvas a pagar mientras verificamos el pedido.',
    'details.close': 'Cerrar detalles', 'details.volume': 'Volumen', 'details.rating': 'valoración en MyAnimeList', 'details.noSynopsis': 'Todavía no hay una sinopsis disponible para este título.', 'details.rentalDay': 'Alquiler por día', 'details.purchase': 'Precio de compra', 'details.oneAvailable': 'unidad disponible', 'details.manyAvailable': 'unidades disponibles', 'details.noneAvailable': 'Sin unidades disponibles', 'details.note': 'Puedes combinar compras y alquileres en el mismo carrito. El stock se reserva por 30 minutos al continuar a Stripe Checkout en modo de prueba.', 'details.addRental': 'Añadir alquiler', 'details.addPurchase': 'Añadir compra', 'details.back': 'Volver al catálogo',
    'checkoutDialog.close': 'Cerrar checkout', 'checkoutDialog.badge': '◉ Stripe · modo de prueba', 'checkoutDialog.title': 'Completa tu pedido', 'checkoutDialog.intro': 'Una sola operación para comprar y alquilar. El inventario se reserva durante 30 minutos mientras pagas.', 'checkoutDialog.day': 'día', 'checkoutDialog.days': 'días', 'checkoutDialog.rent': 'Alquiler', 'checkoutDialog.buy': 'Compra', 'checkoutDialog.unit': 'unidad(es)', 'checkoutDialog.total': 'Total de prueba', 'checkoutDialog.name': 'Nombre completo', 'checkoutDialog.nameHint': 'Tu nombre', 'checkoutDialog.email': 'Correo electrónico', 'checkoutDialog.emailHint': 'tu@correo.com', 'checkoutDialog.missingKeys': 'Stripe está en modo de prueba, pero faltan sus claves de prueba en el backend. El carrito y el inventario no se modificarán hasta iniciar el checkout.', 'checkoutDialog.secure': 'El pago se procesa en la página segura de Stripe. Usa exclusivamente tarjetas de prueba.', 'checkoutDialog.connecting': 'Conectando con Stripe…', 'checkoutDialog.continue': 'Continuar a Stripe', 'checkoutDialog.noUrl': 'Stripe no devolvió la dirección de pago.', 'checkoutDialog.failed': 'No se pudo iniciar el pago. Revisa tu conexión e inténtalo de nuevo.',
    'policy.returnEyebrow': 'Devoluciones', 'policy.returnTitle': 'Devoluciones, sin letra pequeña', 'policy.returnDescription': 'Consulta lo que el sistema puede registrar ahora y qué condiciones todavía no se han definido.', 'policy.returnNotice': 'La tienda pública no ofrece todavía una solicitud de devolución, cambio o reembolso. No hay plazos, métodos de recogida ni importes de compensación confirmados para publicar.', 'policy.rentals': 'ALQUILERES', 'policy.returnRecord': 'Registro de una devolución', 'policy.returnDescriptionLong': 'El equipo puede marcar un alquiler como devuelto desde el panel administrativo. Al registrar la devolución, el sistema guarda la fecha y devuelve una unidad al inventario.', 'policy.internalOnly': 'La gestión es interna por ahora.', 'policy.noPickup': 'El sitio todavía no permite programar una recogida ni consultar un historial personal de devoluciones.', 'policy.purchases': 'COMPRAS Y REEMBOLSOS', 'policy.disabled': 'Estas operaciones aún no están habilitadas', 'policy.noRefunds': 'La tienda permite pagos de prueba mediante Stripe Checkout, pero no acepta cobros reales. Este sistema de prueba todavía no ofrece un flujo comercial para reembolsos, cambios de volumen o cancelaciones posteriores al pago.', 'policy.beforeService': 'ANTES DE ACTIVAR EL SERVICIO', 'policy.conditionsMissing': 'Faltan condiciones aprobadas', 'policy.conditionsMissingText': 'Plazos, estado aceptable de los ejemplares, gastos por daños, métodos de entrega y tiempos de reembolso deben acordarse y añadirse aquí antes de ofrecerlos a clientes.',
    'policy.legalEyebrow': 'Información legal', 'policy.termsTitle': 'Términos y condiciones', 'policy.termsDescription': 'Resumen del alcance de esta versión de MangaGo y de la información que aún falta aprobar.', 'policy.termsNotice': 'Este contenido es un borrador de interfaz, no un documento jurídico revisado. Antes de publicarlo como términos oficiales, el negocio debe validar su identidad legal, jurisdicción, privacidad, propiedad intelectual, medios de pago y condiciones comerciales.', 'policy.scope': '01 · ALCANCE', 'policy.publicCatalog': 'Catálogo público', 'policy.catalogScope': 'La web permite explorar títulos y consultar el catálogo. El carrito puede combinar compras y alquileres y abrir Stripe Checkout en modo de prueba. Este entorno no procesa pagos reales.', 'policy.prices': '02 · DISPONIBILIDAD Y PRECIOS', 'policy.managedInfo': 'Información administrada por el equipo', 'policy.stockInfo': 'Los precios y las cantidades disponibles provienen del inventario administrado en el sistema. Al iniciar un checkout de prueba, la tienda reserva temporalmente las unidades; las sesiones canceladas o vencidas liberan esa reserva.', 'policy.operations': '03 · ALQUILERES Y DEVOLUCIONES', 'policy.preparing': 'Operaciones en preparación', 'policy.rentalOrderInfo': 'El panel interno permite gestionar alquileres, devoluciones y pedidos de prueba. Un pago aprobado en Stripe de prueba genera un pedido y un comprobante interno; las líneas de alquiler también crean sus registros para administrar la devolución. Las reglas comerciales finales deben confirmarse antes de habilitar pagos reales.', 'policy.pendingData': '04 · DATOS Y DERECHOS', 'policy.incomplete': 'Información pendiente de completar', 'policy.dataRights': 'Antes de usar esta página como acuerdo con clientes, se debe publicar la política de privacidad, explicar el tratamiento y la conservación de datos, identificar a la entidad responsable y confirmar los derechos sobre el contenido del catálogo.', 'policy.draftDate': 'Borrador de proyecto · 25 de septiembre de 2026', 'policy.rentalStatus': 'Estado de los alquileres', 'policy.returnStatus': 'Estado de las devoluciones', 'policy.moreInfo': 'Más información',
    'common.light': 'Claro', 'common.dark': 'Oscuro', 'common.spanish': 'Español', 'common.english': 'Inglés', 'info.version': 'Información de esta versión'
  },
  en: {
    'alerts.title': 'Notify me when back in stock',
    'alerts.description': 'Leave your email and we will let you know when this volume is available again.',
    'alerts.email': 'Your email address', 'alerts.submit': 'Notify me', 'alerts.sending': 'Processing…',
    'alerts.consent': 'I want to receive a confirmation email and one availability alert for this volume. I can cancel from the email. The alert expires after 90 days.',
    'alerts.registered': 'Request received. Check your inbox and spam folder, then activate the alert using the link. If already activated, you do not need to register again.',
    'alerts.failed': 'We could not process your request. Please try again in a few minutes.',
    'alerts.rateLimit': 'You have sent several requests. Please wait a few minutes before trying again.',
    'alerts.inStock': 'This volume is already in stock. Close the details and refresh the catalog.',
    'alerts.unavailable': 'Email alerts are temporarily unavailable. Please try again later.',
    'alerts.activateTitle': 'Activate alert', 'alerts.cancelTitle': 'Cancel alert',
    'alerts.manageDescription': 'Confirm your choice to manage this volume’s stock alert.',
    'alerts.invalidLink': 'This link is invalid or has expired. You can request a new alert from the catalog.',
    'alerts.activated': 'Alert activated. We will email you when stock is available. This does not reserve a copy and expires after 90 days.',
    'alerts.cancelled': 'Alert cancelled. You will no longer receive notifications for this subscription.',
    'nav.catalog': 'Catalog', 'nav.new': 'New arrivals', 'nav.collections': 'Collections', 'nav.rentals': 'Rentals', 'nav.help': 'Help', 'nav.cart': 'Cart',
    'nav.main': 'Main navigation', 'nav.open': 'Open menu', 'nav.close': 'Close menu', 'nav.theme': 'Toggle theme', 'nav.language': 'Change language',
    'home.eyebrow': 'Your next read starts here', 'home.title': 'Stories that take you', 'home.titleAccent': 'to other worlds.',
    'home.description': 'Discover your next favorite series. Browse titles and check the price and availability of every volume.',
    'home.explore': 'Explore manga', 'home.how': 'How it works', 'home.volume': 'Details for every volume', 'home.stock': 'Live availability',
    'home.readers': 'Community favorites', 'home.popular': 'Reader favorites', 'home.popularDescription': 'Stories winning over readers in our community.',
    'home.recent': 'New stories', 'home.recentDescription': 'Discover the latest titles added to our catalog.', 'home.loading': 'Loading…',
    'home.trendLoading': 'Finding reader favorites…', 'home.trendEmpty': 'Recommendations will appear here soon.', 'home.arrivalsLoading': 'Loading new arrivals…', 'home.arrivalsEmpty': 'We are preparing more new arrivals for you.', 'home.arrivalsEyebrow': 'Just arrived', 'home.latestDescription': 'Discover the latest titles added to our catalog.', 'home.available': 'Available', 'home.none': 'Out of stock', 'home.rentalDay': 'Rental', 'home.purchasePrice': 'Purchase', 'home.authorEyebrow': 'The creators behind every page', 'home.authorsTitle': 'Authors who leave a mark', 'home.authorsDescription': 'Meet the creators our community is reading most.', 'home.authorsLoading': 'Loading authors…', 'home.authorsEmpty': 'Popular authors will appear here.', 'home.reading': 'Stories that bring us together', 'home.community': 'What the community is reading', 'home.week': '📖 Most read this week', 'home.weekEmpty': 'There are no reading stats to show yet.', 'home.today': '🔥 Most rented today', 'home.todayEmpty': 'Today’s rentals will appear here.', 'home.volumes': 'titles', 'home.titleSingular': 'title', 'home.featured': 'Reader pick', 'home.recommendation': 'A recommendation for you', 'home.featuredDetails': 'See details', 'home.awaiting': 'A new story is waiting for you', 'home.sticker': 'Read at your pace', 'home.collectionsEyebrow': 'Find your next world', 'home.collectionsTitle': 'Read for your mood', 'home.collectionsDescription': 'A starting point for every kind of reader.', 'home.collectionBeginner': 'Start here', 'home.collectionAnime': 'From anime to pages', 'home.collectionHorror': 'Mystery for the night',
    'home.collectionLoading': 'Finding titles…', 'home.collectionEmpty': 'There are no manga in this collection yet.', 'home.scrollCollection': 'Scroll through this collection', 'home.infoEyebrow': 'A catalog to explore', 'home.infoTitle': 'Discover titles and their details.', 'home.exploreStories': 'Explore stories', 'home.browseCollections': 'Browse new arrivals and collections', 'home.findGenres': 'Find titles by genre', 'home.ratings': 'See available ratings', 'home.openDetails': 'Open a manga page', 'home.synopsis': 'Read the author and synopsis', 'home.buyPrice': 'Check the purchase price', 'home.rentalRate': 'See the daily rental rate', 'home.recordedStock': 'Check recorded stock', 'home.internalRentals': 'In-store rentals', 'home.staffRental': 'Staff records the rental', 'home.returnDate': 'A return date is set', 'home.inventoryUpdate': 'The panel updates inventory', 'home.testCheckout': 'Test-mode checkout', 'home.checkoutReserve': 'Stock is reserved when checkout starts', 'home.mixedCart': 'Purchases and rentals share one cart', 'home.testCards': 'Stripe Checkout uses test cards', 'home.serviceStatus': 'View service status',
    'footer.tagline': 'A place to discover stories, try new series, and find your next favorite.', 'footer.help': 'Need help?', 'footer.explore': 'Explore',
    'footer.info': 'Information', 'footer.faq': 'Frequently asked questions', 'footer.return': 'Return policy', 'footer.terms': 'Terms and conditions', 'footer.top': 'Back to top ↑', 'footer.popular': 'Reader favorites', 'footer.rentals': 'Rental policies', 'footer.exploreLabel': 'Explore store', 'footer.infoLabel': 'Information', 'footer.backTop': 'Back to top', 'footer.note': 'One page at a time. A new world in every story.',
    'catalog.eyebrow': 'Your next read', 'catalog.title': 'Explore the catalog', 'catalog.description': 'Find the manga and volume you want. Filter by availability, purchase, or rental.', 'catalog.search': 'Search', 'catalog.manga': 'Manga', 'catalog.allManga': 'All manga', 'catalog.volume': 'Volume', 'catalog.allVolumes': 'All volumes', 'catalog.author': 'Author', 'catalog.allAuthors': 'All authors', 'catalog.availability': 'Availability', 'catalog.allStock': 'Any stock status', 'catalog.available': 'In stock', 'catalog.unavailable': 'Out of stock', 'catalog.mode': 'Format', 'catalog.buyRent': 'Purchase and rental', 'catalog.purchase': 'For purchase', 'catalog.rental': 'For rental', 'catalog.clear': 'Clear filters', 'catalog.loading': 'Loading catalog…', 'catalog.notFound': 'No manga matches these filters. Try changing one.', 'catalog.previous': 'Previous', 'catalog.next': 'Next', 'catalog.retry': 'Retry', 'catalog.foundOne': 'volume found', 'catalog.foundMany': 'volumes found',
    'cart.selection': 'Your selection', 'cart.title': 'Your cart', 'cart.description': 'Combine volumes to buy and rent in one checkout.', 'cart.continue': '← Keep exploring', 'cart.summary': 'Summary', 'cart.order': 'Your order', 'cart.items': 'Items', 'cart.total': 'Estimated total', 'cart.checkout': 'Continue to checkout', 'cart.empty': 'Your cart is empty', 'cart.emptyText': 'Add a volume to buy or rent and it will appear here.', 'cart.explore': 'Explore the catalog', 'cart.remove': 'Remove', 'cart.quantity': 'Quantity', 'cart.days': 'Rental days', 'cart.buy': 'Purchase', 'cart.rent': 'Rental', 'cart.outOfStock': 'Out of stock', 'cart.available': 'in stock', 'cart.insufficient': 'Not enough stock for this cart', 'cart.noReservation': 'Items are not reserved in the cart', 'cart.stockChanged': 'Please review quantities; an item no longer has enough stock.', 'cart.testPayment': 'Stripe Checkout test mode · no real payments are accepted', 'cart.cancelled': 'Payment cancelled. Reserved items were released; you can try again.', 'cart.cancelling': 'Payment was cancelled. The stock reservation is being released; refresh in a few minutes.',
    'faq.center': 'Help center', 'faq.title': 'Answers to keep you reading.', 'faq.intro': 'Learn what the catalog offers and how test-mode purchases and rentals work.', 'faq.view': 'View frequently asked questions', 'faq.useful': 'Helpful information', 'faq.details': 'Looking for all the details?', 'faq.version': 'See what this version of the system can do.', 'faq.rentalPolicies': 'Rental policies', 'faq.returns': 'Returns and refunds', 'faq.terms': 'Terms and conditions', 'faq.next': 'One step from your next story', 'faq.faqs': 'Frequently asked questions', 'faq.searchHint': 'Search a topic or open a question to see its answer.', 'faq.search': 'Search frequently asked questions', 'faq.placeholder': 'Try: rental, payment, or return', 'faq.one': 'result', 'faq.many': 'results', 'faq.notFound': 'We could not find that question', 'faq.tryAgain': 'Try another word, such as rental, delivery, or payment.', 'faq.clear': 'Clear search',
    'faq.q1': 'Can I buy or rent from the store?', 'faq.a1': 'You can combine purchases and rentals in one cart and continue to Stripe Checkout in test mode. Stock is reserved temporarily when checkout starts; approved orders appear under Orders and rentals appear in the admin panel.', 'faq.q2': 'What does the rental price mean?', 'faq.a2': 'The catalog shows the daily rate configured for each volume. The internal panel calculates rental cost from the recorded number of days; rentals cannot yet be started from this storefront.', 'faq.q3': 'How can I check if a volume is available?', 'faq.a3': 'Open a manga card to see the stock currently recorded in the system. This count is informational and does not reserve a copy.', 'faq.q4': 'How is a return recorded?', 'faq.a4': 'Staff currently record returns in the admin panel. The public site does not schedule pickups or provide a personal rental history.', 'faq.q5': 'What are the rental periods and fees?', 'faq.a5': 'Fixed periods, deposits, late fees, discounts, and delivery terms have not been confirmed in this version. They will not be presented as service terms until the business defines them.', 'faq.q6': 'Which payment methods can I use?', 'faq.a6': 'The store uses Stripe Checkout in test mode. Test keys must be configured on the server; no real payments are processed.', 'faq.q7': 'Where can I find all the terms?', 'faq.a7': 'These pages describe each service. If a condition is unclear, review the information for the relevant product before continuing.', 'faq.linkRental': 'Rental status', 'faq.linkHowRental': 'How rentals work', 'faq.linkReturns': 'Return status', 'faq.linkTerms': 'Read project terms', 'faq.linkSystem': 'View system information', 'faq.linkRentals': 'Rentals', 'faq.linkReturn': 'Returns', 'faq.linkTermsShort': 'Terms',
    'policy.rentalEyebrow': 'Rentals', 'policy.rentalTitle': 'How it works today', 'policy.rentalDescription': 'A clear guide to the catalog information and the tasks this version of the system can manage.', 'policy.rentalNotice': 'Final business terms—duration, deposits, late fees, delivery, and payments—still need to be confirmed. This page describes only behavior currently implemented in the app.', 'policy.catalog': 'WHAT YOU CAN CHECK', 'policy.volumePrice': 'Prices and availability by volume', 'policy.volumeDescription': 'The store shows catalog titles, volume number, purchase price, daily rental rate, and units recorded in inventory.', 'policy.internal': 'INTERNAL MANAGEMENT', 'policy.rentalRecords': 'Rental records', 'policy.rentalManagement': 'The admin panel lets staff create a rental for a customer and an in-stock manga, set a return date, and check its status.', 'policy.stock': 'Stock', 'policy.stockDescription': 'Creating a rental reserves one unit. Marking it returned adds that unit back to inventory.', 'policy.calculation': 'Calculation', 'policy.calculationDescription': 'The system calculates rental cost from the daily rate configured for the manga and the days until its return date.', 'policy.payment': 'Payment', 'policy.paymentDescription': 'Store checkout processes test payments through Stripe. Approved rentals are marked paid in the admin panel.', 'policy.pending': 'TO BE DEFINED', 'policy.conditions': 'Business terms', 'policy.conditionsDescription': 'This version does not configure fixed periods, extensions, deposits, discounts, penalties, delivery coverage, or payment methods. Define those values before advertising them as service terms.',
    'checkout.order': 'Store order', 'checkout.receipt': 'Internal receipt', 'checkout.customer': 'Customer', 'checkout.rental': 'rental', 'checkout.purchase': 'purchase', 'checkout.days': 'days', 'checkout.total': 'Total paid', 'checkout.nonFiscal': 'Internal receipt · Not a tax document · Test payment', 'checkout.backCatalog': 'Back to catalog', 'checkout.print': 'Print receipt', 'checkout.backCart': 'Back to cart', 'checkout.explore': 'Explore catalog', 'checkout.confirming': 'Confirming your payment', 'checkout.waiting': 'Stripe returned you to the store. We are waiting for secure payment confirmation; you can leave this page open.', 'checkout.notFound': 'We could not find the session', 'checkout.returnCart': 'Return to your cart to start checkout again.', 'checkout.confirmed': 'Order confirmed!', 'checkout.approved': 'Your test payment was approved, items were assigned, and we saved your receipt.', 'checkout.incomplete': 'Payment was not completed', 'checkout.released': 'No payment was collected and the inventory reservation was released. You can try again.', 'checkout.verifyFailed': 'We could not verify the payment', 'checkout.checkLater': 'Check the order status again in a moment or contact store support.', 'checkout.pending': 'Confirmation is still in progress. Refresh this page in a few seconds; do not pay again while we verify the order.',
    'details.close': 'Close details', 'details.volume': 'Volume', 'details.rating': 'MyAnimeList rating', 'details.noSynopsis': 'A synopsis is not available for this title yet.', 'details.rentalDay': 'Rental per day', 'details.purchase': 'Purchase price', 'details.oneAvailable': 'copy available', 'details.manyAvailable': 'copies available', 'details.noneAvailable': 'No copies available', 'details.note': 'Combine purchases and rentals in one cart. Stock is reserved for 30 minutes when you continue to Stripe Checkout in test mode.', 'details.addRental': 'Add rental', 'details.addPurchase': 'Add purchase', 'details.back': 'Back to catalog',
    'checkoutDialog.close': 'Close checkout', 'checkoutDialog.badge': '◉ Stripe · test mode', 'checkoutDialog.title': 'Complete your order', 'checkoutDialog.intro': 'Buy and rent in one checkout. Inventory is reserved for 30 minutes while you pay.', 'checkoutDialog.day': 'day', 'checkoutDialog.days': 'days', 'checkoutDialog.rent': 'Rental', 'checkoutDialog.buy': 'Purchase', 'checkoutDialog.unit': 'unit(s)', 'checkoutDialog.total': 'Test total', 'checkoutDialog.name': 'Full name', 'checkoutDialog.nameHint': 'Your name', 'checkoutDialog.email': 'Email address', 'checkoutDialog.emailHint': 'you@example.com', 'checkoutDialog.missingKeys': 'Stripe is in test mode, but its test keys are missing from the backend. Cart and stock will not change until checkout starts.', 'checkoutDialog.secure': 'Payment runs on Stripe’s secure page. Use test cards only.', 'checkoutDialog.connecting': 'Connecting to Stripe…', 'checkoutDialog.continue': 'Continue to Stripe', 'checkoutDialog.noUrl': 'Stripe did not return a payment URL.', 'checkoutDialog.failed': 'Could not start payment. Check your connection and try again.',
    'policy.returnEyebrow': 'Returns', 'policy.returnTitle': 'Returns, clearly explained', 'policy.returnDescription': 'See what the system can record now and which terms have not been defined yet.', 'policy.returnNotice': 'The public store does not yet offer return, exchange, or refund requests. There are no confirmed deadlines, pickup methods, or compensation amounts to publish.', 'policy.rentals': 'RENTALS', 'policy.returnRecord': 'Recording a return', 'policy.returnDescriptionLong': 'Staff can mark a rental as returned in the admin panel. The system saves the date and returns one unit to inventory.', 'policy.internalOnly': 'Returns are handled internally for now.', 'policy.noPickup': 'The site cannot schedule a pickup or show a personal return history yet.', 'policy.purchases': 'PURCHASES AND REFUNDS', 'policy.disabled': 'These operations are not enabled yet', 'policy.noRefunds': 'The store supports Stripe Checkout test payments but does not collect real payments. The test system does not yet provide a commercial workflow for refunds, volume exchanges, or post-payment order cancellations.', 'policy.beforeService': 'BEFORE SERVICE LAUNCH', 'policy.conditionsMissing': 'Approved terms are still needed', 'policy.conditionsMissingText': 'Deadlines, acceptable item condition, damage costs, delivery methods, and refund timing must be agreed on and added here before offering them to customers.',
    'policy.legalEyebrow': 'Legal information', 'policy.termsTitle': 'Terms and conditions', 'policy.termsDescription': 'An overview of this MangaGo version and the information that still needs approval.', 'policy.termsNotice': 'This content is an interface draft, not a reviewed legal document. Before publishing it as official terms, the business must validate its legal identity, jurisdiction, privacy, intellectual property, payment methods, and commercial terms.', 'policy.scope': '01 · SCOPE', 'policy.publicCatalog': 'Public catalog', 'policy.catalogScope': 'The site lets visitors browse titles and check the catalog. The cart can combine purchases and rentals and open Stripe Checkout in test mode. This environment does not process real payments.', 'policy.prices': '02 · AVAILABILITY AND PRICES', 'policy.managedInfo': 'Information managed by staff', 'policy.stockInfo': 'Prices and available quantities come from inventory managed in the system. Starting test checkout temporarily reserves units; cancelled or expired sessions release the reservation.', 'policy.operations': '03 · RENTALS AND RETURNS', 'policy.preparing': 'Operations in preparation', 'policy.rentalOrderInfo': 'The admin panel manages rentals, returns, and test orders. An approved Stripe test payment creates an order and internal receipt; rental lines also create records for managing returns. Final business rules must be confirmed before enabling real payments.', 'policy.pendingData': '04 · DATA AND RIGHTS', 'policy.incomplete': 'Information still needed', 'policy.dataRights': 'Before using this page as an agreement with customers, publish a privacy policy, explain data handling and retention, identify the responsible entity, and confirm the rights to catalog content.', 'policy.draftDate': 'Project draft · September 25, 2026', 'policy.rentalStatus': 'Rental status', 'policy.returnStatus': 'Return status', 'policy.moreInfo': 'More information',
    'common.light': 'Light', 'common.dark': 'Dark', 'common.spanish': 'Spanish', 'common.english': 'English', 'info.version': 'Information for this version'
  }
};

export const t = (key: string): string => messages[locale.value][key] ?? key;
export const getLocale = () => locale.value;
export const getTheme = () => theme.value;
export const setLocale = (value: Locale) => { locale.value = value; localStorage.setItem('mangago-locale', value); document.documentElement.lang = value; };
export const setTheme = (value: Theme) => { theme.value = value; localStorage.setItem('mangago-theme', value); document.documentElement.dataset.theme = value; };
export const toggleLocale = () => setLocale(locale.value === 'es' ? 'en' : 'es');
export const toggleTheme = () => setTheme(theme.value === 'light' ? 'dark' : 'light');
export const initializePreferences = () => { setLocale(locale.value); setTheme(theme.value); };
